# Generated by Django 5.0.1 on 2024-01-28 20:02

import cliniqueapp.models
import django.db.models.deletion
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('est_passer', models.BooleanField(default=False)),
                ('diagnostic', models.CharField(max_length=50)),
                ('traitement', models.CharField(max_length=50)),
                ('commentaire', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('medecin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_de_naissance', models.DateField()),
                ('sexe', django_enumfield.db.fields.EnumField(enum=cliniqueapp.models.Sexe)),
                ('Adresse', models.CharField(max_length=70)),
                ('num_tel', models.IntegerField()),
                ('email', models.EmailField(default='email@amodifier.com', max_length=254)),
                ('specialite', django_enumfield.db.fields.EnumField(enum=cliniqueapp.models.Specialite)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('estPasser', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField(default='2000-01-01')),
                ('sexe', django_enumfield.db.fields.EnumField(enum=cliniqueapp.models.Sexe)),
                ('adresse', models.CharField(max_length=50)),
                ('num_tel', models.IntegerField(default=0)),
                ('email', models.EmailField(default='test@domain.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Salle_Consultation',
            fields=[
                ('ID_Salle', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_de_salle', models.IntegerField(default=0)),
                ('Disponibilite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salle_Operation',
            fields=[
                ('salle_ID', models.AutoField(primary_key=True, serialize=False)),
                ('numero_de_salle', models.IntegerField(default=0)),
                ('disponibilite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('remarques', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('dossier_ID', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreation', models.DateField(auto_now_add=True, null=True)),
                ('antecedents', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('consultations', models.ManyToManyField(blank=True, to='cliniqueapp.consultation')),
                ('operations', models.ManyToManyField(blank=True, to='cliniqueapp.operation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('RDV_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='2000-01-01')),
                ('heure', models.TimeField(default='00:00:00')),
                ('service', django_enumfield.db.fields.EnumField(enum=cliniqueapp.models.Specialite)),
                ('titre', models.CharField(default='Consultation', max_length=50)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.medecin')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.operation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.salle_consultation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniqueapp.salle_operation'),
        ),
    ]
