# Generated by Django 5.0.1 on 2024-01-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliniqueapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dateNaissance',
            new_name='date_de_naissance',
        ),
    ]
