# Generated by Django 5.0.1 on 2024-01-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliniqueapp', '0004_rename_date_de_naissance_rdv_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medecin',
            old_name='num_tel',
            new_name='telephone',
        ),
    ]
